### ISSUE TITLE
Add an SFV point to los angeles county map

### ISSUE THREAD

**Issue by mattymcgraw** [machikoyasuda/los-angeles-map#12]
I'm adding a point to the LA County map that represents my home.

**Comment by machikoyasuda** [comment]
Marking as closed.

**Comment by mattymcgraw** [comment]
I added a point in the SFV and a haiku for the valley.

Which <Fingers crossed> closes #12

![image](https://user-images.githubusercontent.com/18272149/34550695-d00e898c-f0c7-11e7-9635-809e7a253ae4.png)

**Comment by machikoyasuda** [comment]
thanks @mattymcgraw !
